social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/109784550162499793
    linkedin: https://www.linkedin.com/posts/brianwisti_logseq-secondbrain-blog-activity-7026211616236982272-jRco
