social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/109746858904246931
    linkedin: https://www.linkedin.com/posts/brianwisti_add-an-obsidian-css-snippet-activity-7023799094020100096-TwUn
