social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/109718751383178761
    linkedin: https://www.linkedin.com/posts/brianwisti_hugo-render-hooks-for-titled-code-blocks-activity-7022000696434556928-PSRJ
