# The URL the site will be built for
base_url = "https://randomgeekery.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Random Geekery"
description = "Collecting my attempts to improve at tech, art, and life"
ignored_content = ["*.rst.txt"]
taxonomies = [
  {name = "tags", paginate_by=10},
  {name = "series", paginate_by=10},
  {name = "category", feed = true, paginate_by=10},
]
highlight_theme = "agola-dark"

generate_feed = true
feed_filename = "index.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
  main_feed_categories = ["blog",]
  # placed here because I need to apply it myself
  feed_limit = 20

  [extra.author]
    name = "Brian Wisti"
    email = "brianwisti@pobox.com"
    [[extra.author.social]]
      service = "Telegram"
      href = "https://t.me/RandomGeek"
      class = "u-url"
      icon = "fa fa-telegram"
    [[extra.author.social]]
      service = "Mastodon"
      href = "https://hackers.town/@randomgeek"
      class = "u-url"
      icon = "fa fa-mastodon"
    [[extra.author.social]]
      service = "Twitter"
      href = "https://twitter.com/brianwisti"
      class = "u-url"
      icon = "fa fa-twitter"
    [[extra.author.social]]
      service = "Liberapay"
      href = "https://liberapay.com/randomgeek"
      class = "u-url"
      icon = "fa fa-liberapay"

[extra.taxonomy.category.post]
  description = "Longer-form content that I gave some thought to."

[extra.taxonomy.category.note]
  description = "Quick thoughts where I just toss it out and move on."
