social:
  syndication:
    linkedin: https://www.linkedin.com/posts/brianwisti_nah-on-copilot-for-now-activity-7075914323344162816-CiqU
    mastodon: https://hackers.town/@randomgeek/110561141687283147
