social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/109996539552339614
    linkedin: https://www.linkedin.com/posts/brianwisti_secondbrain-blog-dendron-activity-7039779011014647808-zEd4?utm_source=share&utm_medium=member_desktop
