social:
  syndication:
    linkedin: https://www.linkedin.com/posts/brianwisti_a-fun-python-turtle-youtube-playlist-activity-7065824023405891584-rjzu?utm_source=share&utm_medium=member_desktop
    mastodon: https://hackers.town/@randomgeek/110403494746004904
