social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/109803845589526251
    linkedin: https://www.linkedin.com/posts/brianwisti_new-config-tangling-workflow-activity-7027446206129737728-ID6h
