social:
  syndication:
    mastodon: https://hackers.town/@randomgeek/110058842352483483
    linkedin: https://www.linkedin.com/posts/brianwisti_stupid-vs-code-vim-tricks-activity-7043773885921599488-qAYr
